name: ArieraJail
version: 1.0.0
desription: Adds jails for criminals
author: X1machinemaker1X
depend: [WorldEdit]
main: me.x1machinemaker1x.arierajail.ArieraJail

commands:
  handcuffs:
    description: Gives handcuffs to the player
    aliases: [cuffs]
  unhandcuff:
    description: Unhandcuffs the player
    aliases: [uncuff]
  timeleft:
    description: Shows time left in your sentence
    aliases: [tl]
  arierajail:
    description: Main command for ArieraJail
    aliases: [aj, ajail]
        
permission:
  arierajail.clearlog:
    default: op
  arierajail.createcell:
    default: op
  arierajail.createjail:
    default: op
  arierajail.createsign:
    default: op
  arierajail.deletecell:
    default: op
  arierajail.deletejail:
    default: op
  arierajail.handcuffs:
    default: op
  arierajail.jaillist:
    default: op
  arierajail.log:
    default: false
  arierajail.log.self:
    default: false
    children:
      arierajail.log: true
  arierajail.log.others:
    default: false
    children:
      arierajail.log: true
  arierajail.log.all:
    default: op
    children:
      arierajail.log: true
      arierajail.log.self: true
      arierajail.log.others: true
  arierajail.reload:
    default: op
  arierajail.setcellspawn:
    default: op
  arierajail.setrelease:
    default: op
  arierajail.putinjail:
    default: false
  arierajail.releasefromjail:
    default: false
  arierajail.handcuffs.bypass:
    default: false
  arierajail.handcuffs.use:
    default: false
  arierajail.playerquit.bypass:
    default: false
  arierajail.admin:
    default: op
    children:
      arierajail.clearlog: true
      arierajail.createcell: true
      arierajail.createjail: true
      arierajail.createsign: true
      arierajail.deletecell: true
      arierajail.deletejail: true
      arierajail.jaillist: true
      arierajail.reload: true
      arierajail.setcellspawn: true
      arierajail.setrelease: true
  arierajail.cop:
    default: false
    children:
      arierajail.handcuffs: true
      arierajail.handcuffs.use: true
      arierajail.putinjail: true
      arierajail.releasefromjail: true
  arierajail.*:
    default: false
    children:
      arierajail.admin: true
      arierajail.cop: true
      arierajail.handcuffs.bypass: true
      arierajail.playerquit.bypass: true